create extension if not exists pgcrypto;

alter table public.profiles
  add column if not exists is_active boolean not null default true;

create table if not exists public.module_access (
  module text primary key,
  label text not null,
  route_path text,
  sort_order integer not null default 0,
  is_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('admin', 'hr', 'manager', 'employee')),
  module text not null references public.module_access(module) on delete cascade,
  can_view boolean not null default false,
  can_create boolean not null default false,
  can_update boolean not null default false,
  can_delete boolean not null default false,
  can_approve boolean not null default false,
  data_scope text not null check (data_scope in ('none', 'own', 'team', 'organization', 'all')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (role, module)
);

insert into public.module_access (module, label, route_path, sort_order, is_enabled)
values ('access_control', 'Access Control', '/access-control', 95, true)
on conflict (module) do update
set
  label = excluded.label,
  route_path = excluded.route_path,
  sort_order = excluded.sort_order,
  is_enabled = excluded.is_enabled;

insert into public.role_permissions (role, module, can_view, can_create, can_update, can_delete, can_approve, data_scope)
values ('admin', 'access_control', true, true, true, false, false, 'all')
on conflict (role, module) do update
set
  can_view = excluded.can_view,
  can_create = excluded.can_create,
  can_update = excluded.can_update,
  can_delete = excluded.can_delete,
  can_approve = excluded.can_approve,
  data_scope = excluded.data_scope;

create table if not exists public.access_grants (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text not null,
  role text not null check (role in ('hr', 'manager', 'employee')),
  department text,
  manager_id uuid references public.profiles(id) on delete set null,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  granted_by uuid references public.profiles(id) on delete set null,
  invite_count integer not null default 1 check (invite_count >= 1),
  last_invited_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists access_grants_last_invited_at_idx on public.access_grants (last_invited_at desc);
create index if not exists access_grants_role_idx on public.access_grants (role);
create index if not exists access_grants_granted_by_idx on public.access_grants (granted_by);

alter table public.module_access enable row level security;
alter table public.role_permissions enable row level security;
alter table public.access_grants enable row level security;

drop policy if exists "Authenticated users can read module access" on public.module_access;
create policy "Authenticated users can read module access"
on public.module_access
for select
using (auth.uid() is not null);

drop policy if exists "Users can read their role permissions" on public.role_permissions;
create policy "Users can read their role permissions"
on public.role_permissions
for select
using (
  role = public.current_app_role()
  or public.current_app_role() = 'admin'
);

drop policy if exists "Admins can read access grants" on public.access_grants;
create policy "Admins can read access grants"
on public.access_grants
for select
using (public.current_app_role() = 'admin');
